### ISSUE TITLE
Fix build for Android

### ISSUE THREAD

**Issue by Oleg-designer** [QuasarApp/Crawl#62]
[Android build bot](https://quasarapp.ddns.net:8043/#/builders/3/builds/205) cant deploy a project please fix this

**Comment by IgorekLoschinin** [comment]
All changes in the build for android are fixed.

**Comment by EndrII** [comment]
Android build not fixed !
i can not see any branches with needed fixes. 
and buildbot say that [android](https://quasarapp.ddns.net:8043/#/builders/3/builds/224) deploy step still failed 

@IgorekLoschinin  What you fixed ?

**Comment by EndrII** [comment]
i begin work on this issue
